// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Fact struct {
	ID            int64
	Bedroom       []string
	Bathroom      []int64
	PlotArea      sql.NullFloat64
	BuiltUpArea   sql.NullFloat64
	View          []int64
	Furnished     sql.NullInt64
	Ownership     sql.NullInt64
	ScCurrencyID  sql.NullString
	UnitOfMeasure sql.NullString
}

type User struct {
	ID                int32
	Name              string
	PhoneNumber       string
	Otp               sql.NullString
	OtpExpirationTime sql.NullTime
}
